In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

### Import csv data as pandas dataframe

In [4]:
df = pd.read_csv("../data/Fertilizer Prediction.csv")

### Show top 5 records

In [16]:
df.head()

,Temperature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26,52,38,Sandy,Maize,37,0,0,Urea
1,29,52,45,Loamy,Sugarcane,12,0,36,DAP
2,34,65,62,Black,Cotton,7,9,30,14-35-14
3,32,62,34,Red,Tobacco,22,0,20,28-28
4,28,54,46,Clayey,Paddy,35,0,0,Urea

In [15]:
df.rename(columns = {'Temparature': 'Temperature'}, inplace = True)

In [6]:
df.shape

(99, 9)

### Check data types

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Temparature      99 non-null     int64
 1   Humidity         99 non-null     int64
 2   Moisture         99 non-null     int64
 3   Soil Type        99 non-null     str
 4   Crop Type        99 non-null     str
 5   Nitrogen         99 non-null     int64
 6   Potassium        99 non-null     int64
 7   Phosphorous      99 non-null     int64
 8   Fertilizer Name  99 non-null     str
dtypes: int64(6), str(3)
memory usage: 7.1 KB

### Check statistics of dataset

In [8]:
df.describe()

       Temparature  Humidity    Moisture   Nitrogen  Potassium  Phosphorous
count    99.000000  99.000000  99.000000  99.000000  99.000000    99.000000
mean     30.282828  59.151515  43.181818  18.909091   3.383838    18.606061
std       3.502304   5.840331  11.271568  11.599693   5.814667    13.476978
min      25.000000  50.000000  25.000000   4.000000   0.000000     0.000000
25%      28.000000  54.000000  34.000000  10.000000   0.000000     9.000000
50%      30.000000  60.000000  41.000000  13.000000   0.000000    19.000000
75%      33.000000  64.000000  50.500000  24.000000   7.500000    30.000000
max      38.000000  72.000000  65.000000  42.000000  19.000000    42.000000

## Insight
- The dataset does not show impossible values (such as negative nutrient levels or unrealistic temperatures), indicating good data quality.
- The mean and median are almost equal for most features, suggesting that the values are fairly evenly distributed without significant skewness, although Nitrogen and especially Potassium show signs of positive skewness.

### Check missing values

In [9]:
df.isnull().sum()

Temparature        0
Humidity           0
Moisture           0
Soil Type          0
Crop Type          0
Nitrogen           0
Potassium          0
Phosphorous        0
Fertilizer Name    0
dtype: int64

There are no missing values in the dataset

### Check duplicate values

In [10]:
df.duplicated().sum()

np.int64(0)

There are no duplicate values in the dataset

### Checking the number of unique values of each column

In [14]:
df.nunique()

Temparature        14
Humidity           13
Moisture           41
Soil Type           5
Crop Type          11
Nitrogen           24
Potassium          13
Phosphorous        32
Fertilizer Name     7
dtype: int64

In [11]:
df["Fertilizer Name"].value_counts()

Fertilizer Name
Urea        22
DAP         18
28-28       17
14-35-14    14
20-20       14
17-17-17     7
10-26-26     7
Name: count, dtype: int64

In [18]:
#define numerical and categorical columns
numeric_features = [feature for feature in df.columns if df[feature].dtype != "str"]
categorical_features = [feature for feature in df.columns if df[feature].dtype == "str"]

#print columns
print(f"We have {len(numeric_features)} numerical features: {numeric_features}")
print(f"We have {len(categorical_features)} categorical features: {categorical_features}")

We have 6 numerical features: ['Temperature', 'Humidity ', 'Moisture', 'Nitrogen', 'Potassium', 'Phosphorous']
We have 3 categorical features: ['Soil Type', 'Crop Type', 'Fertilizer Name']

In [20]:
for col in categorical_features:
    print(df[col].value_counts())

Soil Type
Loamy     21
Sandy     20
Clayey    20
Black     19
Red       19
Name: count, dtype: int64
Crop Type
Sugarcane      13
Cotton         12
Millets        11
Paddy          10
Pulses         10
Wheat           9
Tobacco         7
Barley          7
Oil seeds       7
Ground Nuts     7
Maize           6
Name: count, dtype: int64
Fertilizer Name
Urea        22
DAP         18
28-28       17
14-35-14    14
20-20       14
17-17-17     7
10-26-26     7
Name: count, dtype: int64

### Overall Insights
- The dataset contains 5 soil types, 11 crop types, and 7 fertilizer categories.
- Soil type is well balanced.
- Crop type has minor variation but remains reasonably distributed.
- Fertilizer classes are moderately balanced, making the dataset suitable for multiclass classification.